### PR TITLE
add the source code to get visibility for debugging purpose

### PR DESCRIPTION
**Pull request by miteshvp**
# Description
Needed for debugging some records or nodes

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by miteshvp** [comment]
[test]

**Review by yzainee-zz — APPROVED** [review]
LGTM

**Comment by miteshvp** [comment]
[test]

**Comment by miteshvp** [comment]
[test]

**Pull request merged**
