### PR TITLE
Add test for new scan endpoint

### PR DESCRIPTION
**Pull request by abs51295**
- Tests for the newly introduced scan endpoint are added.
- The old scan endpoint is marked as experimental endpoint.

### CODE REVIEW

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
@abs51295 pls fix the linter issues, very easy in this case (long lines)

**Comment by tisnik** [comment]
Also please check this one:

```
>       assert resp.status_code == 200
E       assert 500 == 200
E        +  where 500 = <Response streamed [500 INTERNAL SERVER ERROR]>.status_code
```

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Pull request merged**
