### PR TITLE
Add experimental endpoint for user scan

### PR DESCRIPTION
**Pull request by abs51295**

### CODE REVIEW

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
@samuzzal-choudhury can you have a look at this?

**Comment by samuzzal-choudhury** [comment]
@abs51295 please merge this.

**Comment by tisnik** [comment]
@abs51295 @samuzzal-choudhury just FYI: these changes caused the unit test coverage drop under 90% (to 78%) right now. I know that this is form of experimental API, but do you plan to make it official some time?

**Comment by abs51295** [comment]
@tisnik yes this will be taken up as a part of upcoming sprint as a stretch goal. /cc @samuzzal-choudhury @miteshvp @sivaavkd .

**Pull request merged**
