### PR TITLE
Removal of cve_sources and code related to it

### PR DESCRIPTION
**Pull request by jparsai**
# Description
As the code related to cve_source is not in use anymore, removing it from the repo

Fixes #APPAI-1202

### CODE REVIEW

**Comment by yzainee** [comment]
[test]

**Comment by yzainee** [comment]
[test]

**Comment by yzainee** [comment]
[test]

**Comment by yzainee** [comment]
[test]

**Comment by jparsai** [comment]
[test]

**Comment by yzainee** [comment]
[test]

**Comment by jparsai** [comment]
[test]

**Comment by yzainee** [comment]
Please squash your commits

**Pull request merged**
