### PR TITLE
parameter and http status modification in the swagger specification

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**

### CODE REVIEW

**Comment by abs51295** [comment]
Tests are failing @samuzzal-choudhury

**Comment by samuzzal-choudhury** [comment]
@abs51295 not because of any change in the PR. Resting.

**Comment by samuzzal-choudhury** [comment]
[test]

**Comment by samuzzal-choudhury** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by samuzzal-choudhury** [comment]
[test]

**Pull request merged**
